export type { ClientAdapter, ClientState } from './adapter.js'
export type { RoleDefinition, RoleCapability } from './role.js'
export type { AggregatedEvent, DedupOptions, HealthCheckOptions, PoolEventMap } from './types.js'
export type { DedupKeyExtractor } from './dedup/extractor.js'
export { DedupPipeline } from './dedup/pipeline.js'
export type { RoutingStrategy, RoutingCandidate } from './routing/strategy.js'
export { StickyStrategy } from './routing/sticky.js'
export { PriorityStrategy } from './routing/priority.js'
export { PriorityStickyStrategy } from './routing/priority-sticky.js'
export { RoutingTable } from './routing/table.js'
export type { RoutingTableOptions } from './routing/table.js'
export { ClientPool } from './pool.js'
export type { ClientPoolOptions } from './pool.js'
