export type { ClientAdapter, ClientState, PoolEmitter } from './adapter'
export type { RoleDefinition, RoleCapability } from './role'
export type { AggregatedEvent, DedupOptions, HealthCheckOptions, PoolEventMap } from './types'
export type { DedupKeyExtractor } from './dedup/extractor'
export { DedupPipeline } from './dedup/pipeline'
export type { RoutingStrategy, RoutingCandidate } from './routing/strategy'
export { StickyStrategy } from './routing/sticky'
export { PriorityStrategy } from './routing/priority'
export { PriorityStickyStrategy } from './routing/priority-sticky'
export { RoutingTable } from './routing/table'
export type { RoutingTableOptions } from './routing/table'
export { ClientPool } from './pool'
export type { ClientPoolOptions } from './pool'
